1      TERUEL                102              NO               80         
2      JAEN                  377              NO               105        
3      GUADALAJARA           326              NO               80         
4      BALEARES              315              SI               7          
5      ZAMORA                341              NO               19         
6      BURGOS                385              NO               86         
7      BARCELONA             385              NO               86         
8      LA RIOJA              283              SI               99         
9      CUENCA                229              NO               105        
10      MURCIA                258              SI               64         
11     ALMERIA               133              NO               42         
12     PALENCIA              309              NO               83         
13     CEUTA                 321              SI               42         
14     TOLEDO                325              SI               29         
15     HUESCA                361              NO               94         
16     LUGO                  300              NO               21         
17     GRANADA               209              NO               15         
18     VALENCIA              324              SI               84         
19     VIZCAYA               252              NO               13         
20     LEON                  367              NO               28         
21     TARRAGONA             338              SI               35         
22     CADIZ                 231              NO               112        
23     ALMERIA               112              NO               49         
24     CANTABRIA             237              NO               31         
25     ASTURIAS              209              NO               29         
26     HUELVA                321              NO               114        
27     CACERES               233              NO               67         
28     PALENCIA              184              SI               93         
29     TENERIFE              188              SI               40         
30     ZARAGOZA              254              SI               64         
31     LA RIOJA              329              NO               66         
32     ALICANTE              299              SI               16         
33     ALBACETE              315              NO               11         
34     BURGOS                279              SI               80         
35     BARAJOZ               180              NO               50         
36     GERONA                313              NO               104        
37     ORENSE                168              SI               89         
38     VIZCAYA               154              NO               120        
39     BARAJOZ               395              NO               51         
40     GRANADA               192              SI               74         
41     TOLEDO                238              NO               104        
42     CACERES               312              NO               116        
43     BALEARES              271              NO               54         
44     VIZCAYA               391              NO               26         
45     LEON                  320              NO               26         
46     BARAJOZ               311              NO               89         
47     NAVARRA               374              NO               10         
48     CASTELLON             311              NO               110        
49     ALMERIA               309              NO               90         
50     VALENCIA              339              NO               106        
51     CACERES               175              SI               81         
52     BALEARES              172              SI               18         
53     JAEN                  205              NO               119        
54     AVILA                 234              NO               80         
55     ALICANTE              279              SI               120        
56     GRANADA               296              SI               88         
57     CEUTA                 355              SI               71         
58     ASTURIAS              221              NO               11         
59     BARCELONA             247              NO               112        
60     ORENSE                213              SI               15         
61     CANTABRIA             232              NO               50         
62     CEUTA                 311              SI               34         
63     PALENCIA              126              NO               17         
64     VALLADOLID            377              NO               67         
65     ASTURIAS              313              NO               18         
66     CIUDAD REAL           278              SI               106        
67     GUADALAJARA           197              NO               3          
68     BURGOS                241              NO               80         
69     ASTURIAS              238              NO               28         
70     NAVARRA               177              NO               69         
71     SEGOVIA               206              NO               84         
72     MALAGA                276              NO               38         
73     SEVILLA               236              SI               29         
74     MADRID                253              NO               61         
75     TARRAGONA             278              SI               107        
76     BARAJOZ               138              SI               30         
77     SEVILLA               190              NO               54         
78     ORENSE                370              SI               42         
79     BURGOS                283              SI               15         
80     LUGO                  368              NO               60         
81     CASTELLON             104              SI               29         
82     SORIA                 192              NO               87         
83     TARRAGONA             119              NO               62         
84     BALEARES              242              NO               4          
85     GUADALAJARA           206              NO               68         
86     CANTABRIA             355              NO               91         
87     CACERES               189              NO               68         
88     GUADALAJARA           299              NO               69         
89     CANTABRIA             394              SI               36         
90     LA RIOJA              298              NO               4          
91     CEUTA                 359              SI               89         
92     LAS PALMAS            272              SI               117        
93     CUENCA                319              NO               3          
94     JAEN                  246              SI               7          
95     CEUTA                 139              NO               8          
96     CORDOBA               311              NO               25         
97     MURCIA                248              NO               89         
98     SORIA                 105              NO               5          
99     GRANADA               111              SI               75         
100     ALMERIA               236              NO               2          
101    SEGOVIA               325              NO               79         
102    TOLEDO                277              NO               97         
103    JAEN                  312              NO               100        
104    LUGO                  101              NO               57         
105    HUESCA                339              NO               116        
106    JAEN                  226              NO               33         
107    MELILLA               198              NO               63         
108    ALMERIA               191              NO               36         
109    BURGOS                374              NO               55         
110    GERONA                309              NO               48         
111    LERIDA                158              SI               23         
112    TENERIFE              275              SI               52         
113    VALLADOLID            367              NO               73         
114    SORIA                 146              NO               38         
115    BURGOS                167              SI               74         
116    MELILLA               234              SI               113        
117    PONTEVEDRA            279              SI               30         
118    LA RIOJA              228              NO               17         
119    CORDOBA               176              NO               19         
120    TENERIFE              347              NO               61         
121    SALAMANCA             350              SI               50         
122    LA RIOJA              213              NO               119        
123    ALMERIA               378              SI               92         
124    CUENCA                276              NO               47         
125    GERONA                172              NO               27         
126    BALEARES              309              SI               9          
127    MELILLA               222              NO               86         
